version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 45
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "Tests/"
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - "**/Test/"
  - "*.test.ts"
  - ".eslintrc.js"
  - "*.index.ts"
  - "**/index.ts"
  
